### PR TITLE
bug(#83): fix stg pull when no upstream is configured

### LINKED ISSUE #83: `stg pull` on a branch without upstream set is causing an Exception
If a particular branch does not have tracking information spits out traceback.

```
Traceback (most recent call last):
  File "/Users/<USER>/Documents/Developer/stgit/stgit/main.py", line 188, in _main
    ret = command.func(parser, options, args)
  File "/Users/<USER>/Documents/Developer/stgit/stgit/commands/pull.py", line 137, in func
    pull(repository, remote_name)
  File "/Users/<USER>/Documents/Developer/stgit/stgit/commands/pull.py", line 78, in pull
    runner.returns([0, 1]).run()
  File "/Users/<USER>/Documents/Developer/stgit/stgit/run.py", line 265, in run
    self._run_noio()
  File "/Users/<USER>/Documents/Developer/stgit/stgit/run.py", line 161, in _run_noio
    self._prep_cmd(),
  File "/Users/<USER>/Documents/Developer/stgit/stgit/run.py", line 88, in _prep_cmd
    return [fsencode_utf8(c) for c in self._cmd]
  File "/Users/<USER>/Documents/Developer/stgit/stgit/run.py", line 88, in <listcomp>
    return [fsencode_utf8(c) for c in self._cmd]
  File "/Users/<USER>/Documents/Developer/stgit/stgit/compat.py", line 28, in fsencode_utf8
    return os.fsencode(s)
  File "/usr/local/opt/python@3.8/bin/../Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 806, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### PR DESCRIPTION
**Pull request by NonLogicalDev**
CLOSES  #83

### CODE REVIEW

File: t/t1210-pull.sh [hunk 1]
```diff
@@ -0,0 +1,41 @@
+#!/bin/sh
+#
+# Copyright (c) 2006 Yann Dirson
```
Comment (jpgrayson) [inline t/t1210-pull.sh:3]: Copy/paste error?

File: t/t1210-pull.sh [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+      stg pull
+    )
+    '
+
+test_expect_success \
+    'Test that pull without upstream setup produces friendly error' \
+    '
+    (cd clone &&
+      stg branch --create without-upstream &&
+      ( stg pull 2>&1 | ( ! grep -q "Traceback" ) ) || ! stg pull 2>&1
```
Comment (jpgrayson) [inline t/t1210-pull.sh:37]: Instead of testing for the absence of a traceback, I'd prefer we test for the presence of our expected error message.

File: t/t1210-pull.sh [hunk 3]
```diff
@@ -0,0 +1,41 @@
+#!/bin/sh
+#
+# Copyright (c) 2006 Yann Dirson
+#
+
+test_description='test
+
+'
```
Comment (jpgrayson) [inline t/t1210-pull.sh:8]: Need better description.

Also, `t1210-pull.sh` is a bit too generic considering there are already four other "pull" test scripts. Please use a more descriptive name for this script.

File: t/t1210-pull.sh (hunk 1 above)
Comment (NonLogicalDev) [reply t/t1210-pull.sh:3]: Removed, artifact of copying another test script.

File: t/t1210-pull.sh (hunk 3 above)
Comment (NonLogicalDev) [reply t/t1210-pull.sh:8]: Agreed, added the description, I missed that field. 

I renamed the test to be more descriptive, though I named it generically just pull because it was testing a generic pull scenario, seems like pull command does not have a generic test to contain common testcases.

File: t/t1210-pull.sh (hunk 2 above)
Comment (NonLogicalDev) [reply t/t1210-pull.sh:37]: Agreed. Fixed

**Comment by jpgrayson** [comment]
Merged. I also pushed a follow-on change to correct a couple things.

Thank you for this PR!
